@startuml
actor "CTO/TechLead"
participant "Tech Radar UI" as UI
participant "Tech Radar API" as API
participant "Tech Radar Database" as DB

"CTO/TechLead" -> UI : Create new Entry
UI -> UI: Validate Input
UI -> API : PUT /technologies/:id
API -> API : Check if user is authorized
API -> API: Validate Input
API -> DB : Check if entry exist
DB --> API:
API -> DB : Update Entry
DB --> API : Return updated Entry
API --> UI : Return updated Entry
@enduml